# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'breakpoint' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  # Pods for breakpoint

end
